---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Создать форму входа для пользователей, в котором должно быть поле для логина, поле для пароля, кнопка отправки формы
  - Форма входа пишет ошибку, если введено неправильное имя пользователя или пароль
  - После неправильно введенных значений в форме входа можно повторить попытку входа без перезагрузки страницы
  - После успешного входа открывается страница с товарами
  - Приложение должно запоминать, что пользователь авторизован. При перезагрузке страницы пользователь должен оставаться авторизованным
  - Создать форму регистрации для пользователей
  - Форма регистрации должна содержать поле логина, поле пароля, поле подтверждения пароля, поле для почты, поле для телефона, кнопку отправки формы 
  - Имя пользователей должно содержать от 3 до 20 символов
  - Пароль должен быть не менее 6 символов
  - Подтверждение пароля должно совпадать с паролем
  - После успешной регистрации открывается страница с товарами
  - После неправильно введенных значений в форме регистрации можно повторить попытку входа без перезагрузки страницы
  - В корзине должна быть возможность указывать/выбирать количество товара
